### ISSUE TITLE
ValueError: PEFT backend is required for this method.

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [aifartist/ArtSpew#19]
(venv) C:\AI\ArtSpew>py artspew.py --xl -p "Space cat cowboy" -c 10 -n 11
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\AI\ArtSpew\venv\Lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ArtSpew\venv\Lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
Keyword arguments {'safety_checker': None, 'requires_safety_checker': False} are not expected by StableDiffusionXLPipeline and will be ignored.
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 14.86it/s]
Using LCM.
The config attributes {'skip_prk_steps': True} were passed to LCMScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
Traceback (most recent call last):
  File "C:\AI\ArtSpew\artspew.py", line 216, in <module>
    main()
  File "C:\AI\ArtSpew\artspew.py", line 182, in main
    artspew = ArtSpew(
              ^^^^^^^^
  File "C:\AI\ArtSpew\artspew.py", line 135, in __init__
    self._sd = sd_class(
               ^^^^^^^^^
  File "C:\AI\ArtSpew\src\stable_diffusion_base.py", line 40, in __init__
    self.configure_pipeline(self._lcm)
  File "C:\AI\ArtSpew\src\stable_diffusion_base.py", line 70, in configure_pipeline
    self.setup_scheduler(self.pipe, lcm)
  File "C:\AI\ArtSpew\src\stable_diffusion_base.py", line 77, in setup_scheduler
    self.load_and_fuse_lcm()
  File "C:\AI\ArtSpew\src\stable_diffusion_base.py", line 118, in load_and_fuse_lcm
    self.pipe.load_lora_weights(adapter_id)
  File "C:\AI\ArtSpew\venv\Lib\site-packages\diffusers\loaders\lora.py", line 1230, in load_lora_weights
    raise ValueError("PEFT backend is required for this method.")
ValueError: PEFT backend is required for this method.

Any tips on how to set up a PEFT backend for this?
https://huggingface.co/docs/peft/en/tutorial/peft_integrations

**Comment by LazyLama** [comment]
This is what worked for me
pip3 install peft
